stages:
  - build
  - test

variables:
  maven_package_cache: ".m2/repository/"
  MAVEN_OPTS: "-Dmaven.repo.local=./$maven_package_cache"

build:
  stage: build
  tags:
    - docker
  cache:
    paths:
      - "$maven_package_cache"
  artifacts:
    name: $CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    expire_in: 1 week
    paths:
      - "ueb03/target/*"
  script:
    - cd ueb03/
    - mvn compile

test:
  stage: test
  tags:
    - docker
  cache:
    paths:
      - "$maven_package_cache"
  script:
    - cd ueb03/
    - mnv test
