name: build adocs

on:
  push
  
jobs:
  adoc_build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get build container
      id: adocbuild
      uses: tonynv/asciidoctor-action@master
      with:
          program: "asciidoctor -D ueb03/doc --backend=html5 -o index.html ueb03/doc/doc.adoc"
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ueb03/doc
