name: Maven CI
on:
  push

env:
  maven_package_cache: ".m2/repository/"
  MAVEN_OPTS: "-Dmaven.repo.local=./$maven_package_cache"

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      working-directory: ueb03
      run: mvn compile
    - name: Get Environment Variables
      run: git_hash=$(git rev-parse --short "$GITHUB_SHA") && git_slug=$(echo $GITHUB_REF | | awk -F'/' '{print $NF}')

    - name: Step 3 - Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
        name: $GITHUB_JOB-$git_slug-$git_hash
        path: target/*
